### ISSUE TITLE
EC2 v1.2 Audio Output device defaults to Pulseaudio on Ubuntu 22.04 LTS 

### ISSUE THREAD

**Issue by 3to5artist** [EmissionControl2/EmissionControl2#110]
For the past few weeks I've been using EC2 v1.1-1 on Ubuntu 22.04 LTS in combination with Jack2.

Today I wanted to have a look at the new features that were implemented last month (many thanks for it!) and installed EC2 v1.2 from source. After the installation the only selectable Audio Output device is Pulseaudio.

I am particularly interested in OSC support and the selectable buffer size.

For now I've reverted to EC2 v1.1 which defaults to Audio Output Device:system and works fine on Ubuntu 22.04 LTS in combination with Jack2.

**Comment by rodneydup** [comment]
Hi, sorry about that! We are getting ready to release v1.2 later this week and I was messing around trying to compile without jack  to help with Pipewire compatibility. I've fixed things in the latest commit so that it will compile with jack support by default. Now, if someone wants to compile without jack so that ec2 works well with Pipewire, they just need to do 'configure.sh pipewire'

Anyway, glad to hear you are excited for the OSC support! We are too. I hope it's intuitive, but if it seems unclear, look for the updated manual with OSC explanations probably going online tomorrow or the next day!

**Comment by 3to5artist** [comment]
Thank you for your quick response! I look forward to testing EC2 v1.2 when it is released. If you would like me to test the pre-release once it is ready, please feel free to drop me a note.

**Comment by rodneydup** [comment]
Just dropping a quick note for you that v1.2 is now released! I hope it works well for you.

**Comment by heinzhar** [comment]
So far it's working fine. I will check midi and osc in the coming week. Many thanks!
